# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Unity-iPhone' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'ChocolatePlatform-SDK-Core', '~> 3.0'
  pod 'ChocolatePlatform-SDK-AdColony', '~> 3.0'
  pod 'ChocolatePlatform-SDK-AppLovin', '~> 3.0'
  pod 'ChocolatePlatform-SDK-Baidu', '~> 3.0'
  pod 'ChocolatePlatform-SDK-Facebook', '~> 3.0'
  pod 'ChocolatePlatform-SDK-Flurry', '~> 3.0'
  pod 'ChocolatePlatform-SDK-Googleadmob', '~> 2.0'
  pod 'ChocolatePlatform-SDK-Mopub', '~> 3.0'
  pod 'ChocolatePlatform-SDK-Tapjoy', '~> 3.0'
  pod 'ChocolatePlatform-SDK-Unity', '~> 4.0'
  pod 'ChocolatePlatform-SDK-Vungle', '~> 3.0'
  pod 'ChocolatePlatform-SDK-Amazon', '~> 2.0'
  pod 'ChocolatePlatform-SDK-Google', '~> 3.0'
  pod 'ChocolatePlatform-SDK-Criteo', '~> 1.0'
end
